// One-way import from your product's code into the harness. No dependencies.
// Configure it in sync.json (see sync.example.json):
//   tokens:     copies CSS variables from your app's stylesheet into tokens.json
//   components: lists the component files in your code in components/inventory.md
// The harness never writes back. Change the source, then run npm run sync again.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import { renderCss, root, tokensCss, tokensJson } from "./build-tokens.mjs";

export const syncFile = join(root, "sync.json");
export const inventoryFile = join(root, "design-system/components/inventory.md");

export class MissingSource extends Error {}

const read = (path) => readFileSync(path, "utf8").replace(/\r\n/g, "\n");
const source = (from) => {
  const path = resolve(root, from);
  if (!existsSync(path)) throw new MissingSource(`can't find ${from}`);
  return path;
};

// CSS variables from the first :root block (or the whole file if there is none)
export const cssVariables = (css) => {
  const block = css.match(/:root\s*\{([^}]*)\}/);
  const body = (block ? block[1] : css).replace(/\/\*[\s\S]*?\*\//g, "");
  return Object.fromEntries([...body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)].map(([, name, value]) => [name, value.trim()]));
};

export function syncedTokens(config, current) {
  const vars = cssVariables(read(source(config.tokens.from)));
  const next = structuredClone(current);
  for (const [path, name] of Object.entries(config.tokens.map ?? {})) {
    if (!(name in vars)) throw new Error(`${name} isn't defined in ${config.tokens.from}`);
    const leaf = path.split(".").reduce((node, key) => (node[key] ??= {}), next);
    leaf.$value = vars[name];
    leaf.$extensions = { ...(leaf.$extensions ?? {}), harness: { source: name } };
  }
  return next;
}

export function syncedInventory(config) {
  const dir = source(config.components.from);
  const extensions = config.components.extensions ?? [".tsx", ".jsx", ".vue", ".svelte", ".astro"];
  const files = readdirSync(dir)
    .filter((file) => extensions.some((ext) => file.endsWith(ext)) && !/\.(test|spec|stories)\./.test(file))
    .sort();
  const shown = relative(root, dir).split(sep).join("/");
  return [
    "# Component inventory",
    "",
    "> Answers: Which components exist in our code?",
    "",
    `<!-- Generated by npm run sync from ${shown}. Don't edit; change the code and run it again. -->`,
    "",
    "Use these before building anything new. Write a spec in `components/<name>.md` only when a component needs rules beyond its code.",
    "",
    "| Component | File |",
    "|---|---|",
    ...files.map((file) => `| ${file.replace(/\.[^.]+$/, "")} | \`${shown}/${file}\` |`),
    "",
  ].join("\n");
}

export const readConfig = () => (existsSync(syncFile) ? JSON.parse(read(syncFile)) : null);

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const config = readConfig();
  if (!config) {
    console.log("No sync.json, so there's nothing to sync. See docs/adopting.md.");
    process.exit(0);
  }
  try {
    if (config.tokens) {
      const tokens = syncedTokens(config, JSON.parse(read(tokensJson)));
      writeFileSync(tokensJson, JSON.stringify(tokens, null, 2) + "\n");
      writeFileSync(tokensCss, renderCss(tokens));
      console.log(`Synced ${Object.keys(config.tokens.map ?? {}).length} tokens from ${config.tokens.from}`);
    }
    if (config.components) {
      const inventory = syncedInventory(config);
      writeFileSync(inventoryFile, inventory);
      console.log(`Listed ${inventory.split("\n").filter((l) => l.startsWith("| ") && !l.startsWith("| Component")).length} components from ${config.components.from}`);
    }
  } catch (error) {
    console.error(`error  ${error.message}`);
    process.exit(1);
  }
}
